/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/adulterant-summary`; params?: Router.UnknownInputParams; } | { pathname: `/antibiotic-control-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/antibiotic-control`; params?: Router.UnknownInputParams; } | { pathname: `/collector-management`; params?: Router.UnknownInputParams; } | { pathname: `/dairy-information`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initial-collection-report`; params?: Router.UnknownInputParams; } | { pathname: `/pasteurization-control-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/pasteurization-control`; params?: Router.UnknownInputParams; } | { pathname: `/pdf-export-selection`; params?: Router.UnknownInputParams; } | { pathname: `/physical-chemical-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/physical-chemical-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/producer-registration`; params?: Router.UnknownInputParams; } | { pathname: `/report-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/report-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/adulterant-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/antibiotic-control-consultation`; params?: Router.UnknownOutputParams; } | { pathname: `/antibiotic-control`; params?: Router.UnknownOutputParams; } | { pathname: `/collector-management`; params?: Router.UnknownOutputParams; } | { pathname: `/dairy-information`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/initial-collection-report`; params?: Router.UnknownOutputParams; } | { pathname: `/pasteurization-control-consultation`; params?: Router.UnknownOutputParams; } | { pathname: `/pasteurization-control`; params?: Router.UnknownOutputParams; } | { pathname: `/pdf-export-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/physical-chemical-analysis`; params?: Router.UnknownOutputParams; } | { pathname: `/physical-chemical-consultation`; params?: Router.UnknownOutputParams; } | { pathname: `/producer-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/report-consultation`; params?: Router.UnknownOutputParams; } | { pathname: `/report-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/adulterant-summary${`?${string}` | `#${string}` | ''}` | `/antibiotic-control-consultation${`?${string}` | `#${string}` | ''}` | `/antibiotic-control${`?${string}` | `#${string}` | ''}` | `/collector-management${`?${string}` | `#${string}` | ''}` | `/dairy-information${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/initial-collection-report${`?${string}` | `#${string}` | ''}` | `/pasteurization-control-consultation${`?${string}` | `#${string}` | ''}` | `/pasteurization-control${`?${string}` | `#${string}` | ''}` | `/pdf-export-selection${`?${string}` | `#${string}` | ''}` | `/physical-chemical-analysis${`?${string}` | `#${string}` | ''}` | `/physical-chemical-consultation${`?${string}` | `#${string}` | ''}` | `/producer-registration${`?${string}` | `#${string}` | ''}` | `/report-consultation${`?${string}` | `#${string}` | ''}` | `/report-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/adulterant-summary`; params?: Router.UnknownInputParams; } | { pathname: `/antibiotic-control-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/antibiotic-control`; params?: Router.UnknownInputParams; } | { pathname: `/collector-management`; params?: Router.UnknownInputParams; } | { pathname: `/dairy-information`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initial-collection-report`; params?: Router.UnknownInputParams; } | { pathname: `/pasteurization-control-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/pasteurization-control`; params?: Router.UnknownInputParams; } | { pathname: `/pdf-export-selection`; params?: Router.UnknownInputParams; } | { pathname: `/physical-chemical-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/physical-chemical-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/producer-registration`; params?: Router.UnknownInputParams; } | { pathname: `/report-consultation`; params?: Router.UnknownInputParams; } | { pathname: `/report-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
