# Generated by Django 5.2.8 on 2025-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], max_length=10)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('cad_pro', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_inscricao_estadual', models.CharField(choices=[('CONTRIBUINTE_DE_ICMS', 'Contribuinte de ICMS'), ('NAO_CONTRIBUINTE_DE_ICMS', 'Não contribuinte de ICMS'), ('CONTRIBUINTE_ISENTO', 'Contribuinte isento')], max_length=30)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
