# Generated by Django 5.2.7 on 2025-11-12 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('motorista', '__first__'),
        ('produtor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(verbose_name='Data e Hora da Coleta')),
                ('numero_tanque_produtor', models.CharField(max_length=50, verbose_name='Nº Tanque na Propriedade')),
                ('temperatura_coleta', models.FloatField(verbose_name='Temperatura (02-09ºC)')),
                ('alizarol_coleta', models.FloatField(verbose_name='Alizarol (75-80ºGL)')),
                ('status', models.CharField(choices=[('C', 'Coletado'), ('NC', 'NaoColetado')], max_length=2, verbose_name='Status (C/NC)')),
                ('coletado', models.BooleanField(default=True, help_text='Desmarcar se o leite foi rejeitado e não coletado')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_realizadas', to='motorista.motorista')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_coletados', to='produtor.produtor')),
                ('responsavel_carregamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_supervisionadas', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_transportados', to='motorista.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da NC')),
                ('descricao', models.TextField(verbose_name='Descrição da Não Conformidade')),
                ('acao_corretiva', models.TextField(verbose_name='Descrição da Ação Corretiva')),
                ('prazo_execucao', models.DateField(blank=True, null=True, verbose_name='Prazo para Realização')),
                ('data_retomada', models.DateTimeField(blank=True, null=True, verbose_name='Retomada (Data e Hora)')),
                ('verificacao_execucao', models.TextField(blank=True, null=True, verbose_name='Verificação da Execução')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsavel_acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
