# Generated by Django 5.2.8 on 2025-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseFisicoQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('acidez', models.FloatField(verbose_name='Acidez (%)')),
                ('densidade', models.FloatField(verbose_name='Densidade (g/cm³)')),
                ('crioscopia', models.FloatField(verbose_name='Crioscopia (°C)')),
                ('gordura', models.FloatField(verbose_name='Gordura (%)')),
                ('proteina', models.FloatField(verbose_name='Proteína (%)')),
                ('esd', models.FloatField(verbose_name='ESD')),
                ('est', models.FloatField(verbose_name='EST')),
                ('lactose', models.FloatField(verbose_name='Lactose (%)')),
                ('antibioticos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antibióticos')),
                ('conservantes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conservantes')),
                ('analista', models.CharField(max_length=200, verbose_name='Analista Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
