# Generated by Django 5.2.8 on 2025-12-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_analisefisicoquimica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAntibiotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('resultado', models.CharField(max_length=200, verbose_name='Resultado')),
                ('status', models.CharField(choices=[('compliant', 'Regular'), ('non-compliant', 'Irregular')], max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Pessoa Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlePasteurizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('teste_fosfatase', models.CharField(max_length=100, verbose_name='Teste de Fosfatase')),
                ('teste_peroxidase', models.CharField(max_length=100, verbose_name='Teste de Peroxidase')),
                ('status', models.CharField(choices=[('compliant', 'Regular'), ('non-compliant', 'Irregular')], max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Pessoa Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumoAdulterantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('codigo_produtor', models.CharField(max_length=50, verbose_name='Código Produtor')),
                ('nome_produtor', models.CharField(max_length=200, verbose_name='Nome Produtor')),
                ('adulterantes', models.TextField(verbose_name='Adulterantes')),
                ('padroes_fisico_quimicos', models.TextField(verbose_name='Padrões Físico-Químicos')),
                ('analista', models.CharField(max_length=200, verbose_name='Analista Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
