# Generated by Django 5.2.7 on 2025-11-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_litro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
