# Generated by Django 5.2.8 on 2025-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laticinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('regime_tributario', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('produtores', models.ManyToManyField(related_name='laticinios', to='produtor.produtor')),
            ],
        ),
    ]
