# Generated by Django 5.2.7 on 2025-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=20, verbose_name='CNH'),
        ),
    ]
