# Generated by Django 5.2.7 on 2025-11-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0002_motorista_cpf_motorista_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='veiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='motorista.veiculo'),
        ),
    ]
